name: Deploy

on:
  push:
    tags:
      - '*'

env:
  APIFY_TEST_USER_ID: ${{ secrets.APIFY_TEST_USER_ID }}
  APIFY_TEST_TOKEN: ${{ secrets.APIFY_TEST_TOKEN }}
  IMAGE_NAME: keboola-component
  KBC_APP_ID: apify.apify
  KBC_VENDOR: apify
  KBC_DEVELOPER_PORTAL_USER: apify+service_account

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }} .

#      - name: Run Tests
#        run: docker run -e APIFY_TEST_USER_ID -e APIFY_TEST_TOKEN ${{ env.IMAGE_NAME }} npm test

      - name: Push image
        uses: odinuv/action-push-to-ecr@master
        with:
          vendor: ${{ env.KBC_VENDOR }}
          app_id: ${{ env.KBC_APP_ID }}
          username: ${{ env.KBC_DEVELOPER_PORTAL_USER }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ github.ref }}
          push_latest: true
          source_image: ${{ env.IMAGE_NAME }}

      - name: Deploy to production
        uses: keboola/action-set-tag-developer-portal@master
        with:
          vendor: ${{ env.KBC_VENDOR }}
          app_id: ${{ env.KBC_APP_ID }}
          username: ${{ env.KBC_DEVELOPER_PORTAL_USER }}
          password: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
          tag: ${{ github.ref }}
